// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ryufndizeesyagnhskph.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ5dWZuZGl6ZWVzeWFnbmhza3BoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU2NjI5MTEsImV4cCI6MjA2MTIzODkxMX0.Xuq56dwM7snSGW6sTl0ArPer1n5qrXsepBLLeu7g7sM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);